### ISSUE TITLE
Error in building debian package

### ISSUE THREAD

**Issue by lionfood** [openSUSE/obs-service-set_version#84] opened 2023-03-20 11:06 UTC
When trying to build the debian package from [openSUSE:Tools/obs-service-set_version](https://build.opensuse.org/package/show/openSUSE:Tools/obs-service-set_version) with `osc build --local-package xUbuntu_22.10` the build fails with this as the last messages: 

```
[   54s] ======================================================================
[   54s] FAIL: test_python_version_pip2rpm_10___1_7_40_svn___None_ (test_python_pip2rpm.VersionConverterTest)
[   54s] See https://www.python.org/dev/peps/pep-0440/        #examples-of-compliant-version-schemes
[   54s] ----------------------------------------------------------------------
[   54s] Traceback (most recent call last):
[   54s]   File "/usr/lib/python3/dist-packages/ddt.py", line 191, in wrapper
[   54s]     return func(self, *args, **kwargs)
[   54s]   File "/usr/src/packages/BUILD/tests/test_python_pip2rpm.py", line 129, in test_python_version_pip2rpm
[   54s]     self.assertEqual(rpm_ver, expected_ver)
[   54s] AssertionError: '1.7.40~svn' != None
[   54s] 
[   54s] ----------------------------------------------------------------------
[   54s] Ran 99 tests in 42.954s
[   54s] 
[   54s] FAILED (failures=1, skipped=20)
[   54s] make[1]: *** [Makefile:15: test] Error 1
[   54s] make[1]: Leaving directory '/usr/src/packages/BUILD'
[   54s] dh_auto_test: error: make -j1 test returned exit code 2
[   54s] make: *** [debian/rules:8: build] Error 25
[   54s] dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
[   54s] 
[   54s] linux.fritz.box failed "build debian.dsc" at Mon Mar 20 11:02:19 UTC 2023.
[   54s] 

The buildroot was: /var/tmp/build-root/xUbuntu_22.10-x86_64

```

**Comment by M0ses** [comment] 2024-05-02 19:03
AFAICS here is the root cause of this issue:

 https://github.com/openSUSE/obs-service-set_version/blob/master/set_version#L30

We have 3 different states:

* packaging not installed
* packaging installed (import LegacyVersion succeed)
* packaging installed (import LegacyVersion failed)

so at least we have 2 different results (version_rpm/None) in 

https://github.com/openSUSE/obs-service-set_version/blame/master/set_version#L373

depending if packaging is installed or not on the system.

IMHO this is a no-go but I would like to get some input from @toabctl, @dirkmueller and @adrianschroeter about the background.

**Comment by bluca** [comment] 2024-05-05 11:27
This is a different issue from what is currently happening on Ubuntu 24.04, which seems like a build environment/test setup problem:

```
[   21s] ImportError: Failed to import test module: test_base
[   21s] Traceback (most recent call last):
[   21s]   File "/usr/lib/python3.12/unittest/loader.py", line 394, in _find_test_path
[   21s]     module = self._get_module_from_name(name)
[   21s]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[   21s]   File "/usr/lib/python3.12/unittest/loader.py", line 337, in _get_module_from_name
[   21s]     __import__(name)
[   21s]   File "/usr/src/packages/BUILD/tests/test_base.py", line 18, in <module>
[   21s]     import imp
[   21s] ModuleNotFoundError: No module named 'imp'
```

**Comment by bluca** [comment] 2024-05-08 12:15
> This is a different issue from what is currently happening on Ubuntu 24.04, which seems like a build environment/test setup problem:
> 
> ```
> [   21s] ImportError: Failed to import test module: test_base
> [   21s] Traceback (most recent call last):
> [   21s]   File "/usr/lib/python3.12/unittest/loader.py", line 394, in _find_test_path
> [   21s]     module = self._get_module_from_name(name)
> [   21s]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [   21s]   File "/usr/lib/python3.12/unittest/loader.py", line 337, in _get_module_from_name
> [   21s]     __import__(name)
> [   21s]   File "/usr/src/packages/BUILD/tests/test_base.py", line 18, in <module>
> [   21s]     import imp
> [   21s] ModuleNotFoundError: No module named 'imp'
> ```
> 
> Probably due to new Python version or some other dependency

this was fixed by https://github.com/openSUSE/obs-service-set_version/commit/f11e35645e68888284e0a05e43baf6c4b56ceb4b

**Closed** 2024-05-08 14:00 UTC
