### ISSUE TITLE
set_version doesn't update version field in PKGBUILD

### ISSUE THREAD

**Issue by mmetak** [openSUSE/obs-service-set_version#21] opened 2015-08-19 05:34 UTC
Example: https://build.opensuse.org/package/show/home:metakcahura/sway-git

**Comment by dg0yt** [comment] 2015-08-29 19:48
Since b5cadd8c1e11e3c0fdc987377bf5d28e51f8f1b8, there is no code to set **pkgver** and **pkgrel**. My local set_version is older and works, but on build.opensuse.org, the fields remain unchanged by set_version, causing builds to fail. It seems there is also no testcase covering this simple case.

**Comment by toabctl** [comment] 2015-08-30 09:17
@mmetak , @dg0yt Could you test the fix provided by https://github.com/openSUSE/obs-service-set_version/pull/22 ?

**Comment by dg0yt** [comment] 2015-08-30 10:23
#22 seems to work for me, locally.

It might be helpful if set_version would add a comment like "Modified by set_version x.y.z" on each file it touches.

**Comment by mmetak** [comment] 2015-08-30 13:35
Haven't tried it locally, but it's still broken on the remote it seems. Here's my project page: https://build.opensuse.org/project/monitor/home:metakcahura:arch-lxqt
File _service:set_version:PKGBUILD is not updated with the latest version.

**Comment by toabctl** [comment] 2015-08-30 16:55
> Haven't tried it locally, but it's still broken on the remote it seems. Here's my project page: https://build.opensuse.org/project/monitor/home:metakcahura:arch-lxqt
> File _service:set_version:PKGBUILD is not updated with the latest version.

Well It's not deployed yet. Needs to be merged first and then @adrianschroeter can deploy it on the server.

**Comment by mmetak** [comment] 2015-08-30 18:16
silly me. sorry about that.

**Closed** 2015-09-03 07:21 UTC

**Comment by dg0yt** [comment] 2015-09-07 06:20
For the record, I can confirm that build.opensuse.org now works correctly.
