### ISSUE TITLE
Make set_version detect version when v0.1 style version numbers are used

### ISSUE THREAD

**Issue by seccubus** [openSUSE/obs-service-set_version#30] opened 2016-02-26 16:23 UTC
When building from source the version number can be taken from git tags like this:

```
  <service name="tar_scm">
    <param name="scm">git</param>
    <param name="url">https://github.com/seccubus/obs_autobuild_test</param>
    <param name="filename">obs_autobuild_test</param>
    <param name="versionformat">@PARENT_TAG@.@TAG_OFFSET@</param>
    <param name="filename">obs_autobuild_test</param>
  </service>
```

When you create a release on GitHub it recommends that you create your tags like this: v0.1

If you tag you version like this, your build breaks with the cryptic message:

```
Files could not be expanded: Running /usr/lib/obs/service/set_version --outdir /lxc.tmp.29937/out
```

It would be great if set_version could still detect the version even if it is appened with a v.

**Comment by aspiers** [comment] 2016-08-09 13:01
Isn't this a duplicate of #24?

**Comment by seccubus** [comment] 2016-08-09 13:09
They both point to the same lack of functionality, but the discussion in #24 seems to ask for more then what I ask for here.

**Comment by seccubus** [comment] 2016-08-09 13:10
If this one is closed then PR #32 needs to point to #24 

Honestly since this was raised over half a year ago an has gotten 0 real response I guess we just have to work around it.

**Comment by aspiers** [comment] 2016-08-09 14:30
Who are the maintainers of this repo?

**Comment by adrianschroeter** [comment] 2017-03-02 08:38
set_version is not the right place, because spec and tar ball needs to be in sync. We need to solve this in obs_scm/tar_scm service.

**Closed by adrianschroeter** 2017-03-02 08:38 UTC
